import type { Ability } from './types'

export const CLASS_ABILITIES: Record<string, Record<number, Ability>> = {
  Fighter: {
    1: { name: 'Second Wind', description: 'Once per rest, heal 1d10 + your level as a bonus action.', mechanic: 'hpChange: +(1d10 + level), max level=character.level. Set isRest:false. Heal immediately, no roll needed. Cooldown 1.' },
    3: { name: 'Action Surge', description: 'Once per rest, take one additional action on your turn.', mechanic: 'This turn the Fighter acts twice. Apply double hpChange on attack (if attacking), or accomplish two things in one action. Describe the surge of martial energy. Cooldown 1.' },
    5: { name: 'Extra Attack', description: 'Attack twice whenever you take the Attack action.', mechanic: 'On any attack action, the Fighter strikes twice. Add +50% to combat damage hpChange values (e.g. -8 becomes -12). Narrate the second strike explicitly.' },
    10: { name: 'Indomitable', description: 'Reroll a failed saving throw once per rest.', mechanic: 'When the Fighter would suffer a negative effect from a saving throw failure, they may reroll. On this second attempt, use +4 to the roll. If the reroll succeeds, negate the bad effect. Cooldown 1.' },
  },
  Wizard: {
    1: { name: 'Arcane Recovery', description: 'Once per day during a short rest, recover expended spell slots totaling half your level.', mechanic: 'When the Wizard rests, restore 2 uses of spellcasting power. Narrate as magical energy flowing back into their focus. hpChange: 0 (this is resource recovery, not healing). Set isRest:true context. Cooldown 1.' },
    3: { name: 'Spell Sculpting', description: 'Shape your area spells to exclude allies from their effects.', mechanic: 'When casting an area-effect spell, allies in the blast zone take no damage and suffer no effects. Narrate the Wizard\'s precise magical control. The attack hpChange still applies to enemies.' },
    5: { name: 'Potent Cantrip', description: 'Your cantrip spells deal full damage even on a successful save.', mechanic: 'Enemy saving throws against the Wizard\'s spells still deal half damage on success instead of zero. Add +3 to hpChange on enemies even when their roll succeeds. Narrate the spell\'s relentless force.' },
    10: { name: 'Spell Mastery', description: 'Choose one 1st and one 2nd level spell — cast them at will without a spell slot.', mechanic: 'The Wizard can cast two signature spells (player\'s choice of flavor) without any limit — they never run out of these. Apply appropriate hpChange/statusEffectChanges for the chosen spell effects each time.' },
  },
  Rogue: {
    1: { name: 'Sneak Attack', description: 'Deal an extra 1d6 damage when you have advantage or an ally adjacent to your target.', mechanic: 'When attacking from stealth, from behind, or with an ally nearby, add 1d6 (avg 3-4) extra damage to hpChange. At higher levels scale up: level 5+ add 2d6, level 9+ add 3d6. Narrate the precise strike.' },
    3: { name: 'Uncanny Dodge', description: 'When an attacker you can see hits you, use your reaction to halve the damage.', mechanic: 'Once per round, when the Rogue is hit by an attack they can see coming, halve the incoming hpChange damage. Narrate the fluid dodge or parry. Apply: hpChange = hpChange / 2 (round up).' },
    5: { name: 'Evasion', description: 'When you succeed on a Dexterity save, you take no damage; on a failure, only half.', mechanic: 'On area-effect attacks (traps, explosions, breath weapons): success = hpChange:0 (no damage at all). Failure = hpChange is halved. Narrate the Rogue rolling clear of the effect.' },
    10: { name: 'Reliable Talent', description: 'Treat any d20 roll of 9 or lower as a 10 on ability checks using your proficiencies.', mechanic: 'For skill checks the Rogue is trained in (stealth, lockpicking, acrobatics, slight-of-hand, deception), treat any roll below 10 as a 10. Set DC modifier to +2 on all proficiency checks. Narrate smooth competence.' },
  },
  Cleric: {
    1: { name: 'Divine Domain', description: 'Channel the power of your deity to cast domain spells and shape divine energy around you.', mechanic: 'The Cleric can heal themselves or an ally for 1d8+3 HP once per scene as their deity\'s power flows through them. hpChange: +(1d8+3, avg 7-8). Narrate a divine glow or holy warmth. Cooldown 1.' },
    3: { name: 'Channel Divinity', description: 'Once per rest, channel divine energy to power sacred effects such as Turn Undead or domain abilities.', mechanic: 'Against undead or corrupted enemies, the Cleric can force a morale check. On success (DC 14), the enemy flees or is stunned for 2 rounds (statusEffectChanges.add: Turned, debuff, duration 2). Against any enemy, can add +1d6 radiant hpChange to next attack. Cooldown 1.' },
    5: { name: 'Divine Intervention', description: 'Call on your deity for aid; roll d100 — on a result ≤ your level, the deity intervenes.', mechanic: 'Once per campaign arc, the Cleric calls for miraculous aid. Success chance = character level (e.g., 40% at level 5). On success: dramatic divine intervention — heal to full HP, or smite an enemy for -20 HP, or create a narrative miracle. Describe as a genuine holy moment. Cooldown: once per act.' },
    10: { name: 'Blessed Strikes', description: 'Once per turn, deal an extra 1d8 radiant damage on a weapon or cantrip attack.', mechanic: 'Add +5 radiant damage (1d8 avg) to one attack per turn. The weapon or cantrip glows with holy light. Apply: hpChange gets -5 bonus damage on the main attack. Undead and fiends take double this bonus (-10 instead).' },
  },
  Ranger: {
    1: { name: 'Favored Enemy', description: 'Choose a creature type. You have advantage on Survival checks to track them and on Intelligence checks to recall information about them.', mechanic: 'Against the Ranger\'s chosen enemy type (beasts, undead, bandits, etc.), all attack hpChange values get +3 bonus, and tracking/knowledge rolls get +4. Narrate the Ranger\'s practiced eye and muscle memory against this foe type.' },
    3: { name: 'Natural Explorer', description: 'Difficult terrain costs no extra movement in your favored terrain; you are rarely surprised there.', mechanic: 'In wilderness, forests, or favored terrain: the Ranger cannot be ambushed (always detect threats first). Travel is faster — skip travel complications. Any stealth/survival roll in natural terrain gets +3. Narrate their reading of the land.' },
    5: { name: 'Extra Attack', description: 'Attack twice whenever you take the Attack action.', mechanic: 'The Ranger looses two arrows or strikes twice per combat action. Add +50% to combat damage hpChange values. If using a bow, specifically narrate both arrows finding their mark.' },
    10: { name: 'Hide in Plain Sight', description: 'Spend 1 minute camouflaging yourself; gain +10 to Stealth while you remain still.', mechanic: 'When the Ranger takes time to camouflage (in a natural setting), they become nearly undetectable. Stealth checks auto-succeed against non-magical detection. Enemies cannot target them until they move or attack. Narrate the hunter melding into shadow and bark.' },
  },
  Paladin: {
    1: { name: 'Divine Smite', description: 'On a melee hit, expend a spell slot to deal an extra 2d8 radiant damage per slot level.', mechanic: 'On any melee hit, the Paladin can smite: add -10 extra radiant damage to hpChange (2d8 avg). Against undead and fiends, double the smite to -20. Narrate the weapon blazing with holy light. Cooldown 2.' },
    3: { name: 'Divine Health', description: 'The divine magic flowing through you makes you immune to disease.', mechanic: 'The Paladin cannot be afflicted by disease, poison effects, or corruption statusEffects. If a Poisoned or Diseased status would be added, prevent it and describe the divine aura burning it away. Ongoing: passive immunity, no cooldown.' },
    5: { name: 'Extra Attack', description: 'Attack twice whenever you take the Attack action.', mechanic: 'The Paladin strikes twice per combat action. Add +50% to combat damage hpChange. On the second strike, they can choose to smite for free (add -5 radiant to second hit). Narrate the relentless holy warrior.' },
    10: { name: 'Aura of Protection', description: 'Allies within 10 feet add your Charisma modifier to all saving throws.', mechanic: 'All allies in the same scene add +3 to any saving throws. When allies would fail a DC check (non-combat), they get a second chance with +3. Narrate the golden aura radiating from the Paladin. Passive, no cooldown.' },
  },
  Barbarian: {
    1: { name: 'Rage', description: 'Enter a battle fury: advantage on Strength checks and saves, bonus damage on attacks, and resistance to physical damage for 1 minute.', mechanic: 'While raging: all attack hpChange values get +4 bonus damage. All incoming physical damage is halved (hpChange halved). Add statusEffectChanges.add: Raging (buff, duration 3). Narrate the primal fury taking over. Cooldown 2.' },
    3: { name: 'Reckless Attack', description: 'Attack with advantage on the first attack each turn, but attackers gain advantage against you until your next turn.', mechanic: 'The Barbarian attacks recklessly: add +6 to attack hpChange (reckless power). But incoming enemy hpChange is +3 higher this round (they hit harder against the exposed Barbarian). Net: high risk, high reward. Narrate berserker abandon.' },
    5: { name: 'Extra Attack', description: 'Attack twice whenever you take the Attack action.', mechanic: 'The Barbarian swings twice. Add +50% to combat damage hpChange. If Raging, the bonus damage applies to both hits. Narrate the savage assault.' },
    10: { name: 'Relentless Rage', description: 'When reduced to 0 HP while raging, make a DC 10 Constitution save — on success, drop to 1 HP instead.', mechanic: 'When the Barbarian would reach 0 HP while Raging, automatically succeed the save (this is legendary toughness). Set hpChange to leave them at 1 HP instead of 0. Narrate the impossible refusal to fall. Cooldown: once per rage.' },
  },
  Bard: {
    1: { name: 'Bardic Inspiration', description: 'Bestow a creature a d6 Inspiration die to add to an ability check, attack, or save within 10 minutes.', mechanic: 'The Bard inspires an ally (or themselves): grant statusEffectChanges.add: Inspired (buff, duration 2). While Inspired, +3 to all rolls. Narrate the musical phrase or stirring words. Cooldown 1.' },
    3: { name: 'Jack of All Trades', description: 'Add half your proficiency bonus to any ability check you are not proficient in.', mechanic: 'The Bard succeeds at tasks they\'re not trained in more often than expected. Add +2 to all skill checks outside their expertise. Narrate the breadth of their life experience. Passive, no cooldown.' },
    5: { name: 'Font of Inspiration', description: 'Regain all Bardic Inspiration uses after a short or long rest.', mechanic: 'After any rest, the Bard\'s Bardic Inspiration is fully restored. On a short rest (10+ min), they can immediately give Inspired status to up to 2 allies. hpChange: 0 (resource reset). Narrate the songs washing over the camp.' },
    10: { name: 'Magical Secrets', description: 'Learn two spells from any class, adding them permanently to your spell list.', mechanic: 'The Bard has mastered two signature spells from other traditions (player chooses flavor — healing, fire, illusion, etc.). These can be used once per scene without cost. Apply appropriate hpChange or statusEffectChanges. Narrate the unusual magical style.' },
  },
  Druid: {
    1: { name: 'Wild Shape', description: 'Magically transform into a beast you have seen before, twice per short rest.', mechanic: 'The Druid transforms into a beast (wolf, bear, eagle, etc.). In beast form: gain temporary HP equal to the beast\'s toughness (wolf: +8 HP, bear: +15 HP). Can perform tasks suited to the animal. Revert when temp HP depletes. Cooldown 2.' },
    3: { name: 'Wild Shape Improvement', description: 'Your Wild Shape can now take the form of beasts with a swim speed or up to CR 1.', mechanic: 'Wild Shape now includes swimming creatures (crocodile, shark) and stronger beasts (dire wolf: +20 temp HP, giant spider: venomous, statusEffectChanges.add: Poisoned on enemy). Cooldown 2.' },
    5: { name: 'Timeless Body', description: 'Your body ages only one year for every ten years, and you are immune to magical aging effects.', mechanic: 'The Druid resists magical corruption and aging effects. All disease and curse statusEffects targeting aging, rot, or life drain are automatically negated. When in nature, passive regeneration of 1 HP per scene. Narrate ancient vitality.' },
    10: { name: 'Beast Spells', description: 'Cast Druid spells even while in Wild Shape, provided the spell has no material components.', mechanic: 'While in beast form, the Druid can still cast spells — combining animal power with magic. Beast form attack + spell in same turn: apply both hpChange values. Narrate the uncanny sight of a wolf summoning thorns.' },
  },
  Monk: {
    1: { name: 'Martial Arts', description: 'Use Dexterity instead of Strength for unarmed strikes and monk weapons, and deal 1d4 unarmed damage.', mechanic: 'Unarmed strikes deal -4 damage (1d4). After any melee attack, the Monk can strike again as a bonus action for -3 additional damage. Narrate the precise, economical strikes trained over years.' },
    3: { name: 'Ki', description: 'Spend Ki points to Flurry of Blows, use Patient Defense (Dodge), or Step of the Wind (Dash/Disengage).', mechanic: 'Three options per turn (use one):\n• Flurry of Blows: two extra attacks, hpChange +8 additional damage total.\n• Patient Defense: incoming damage halved this round (hpChange halved).\n• Step of the Wind: automatically escape grapples, traps, surrounded situations — narrate as ghostly movement. Cooldown 1 (per option).' },
    5: { name: 'Stunning Strike', description: 'Spend 1 Ki on a hit to force a Constitution save or stun the target until the end of your next turn.', mechanic: 'On any successful melee hit, the Monk can stun the target: statusEffectChanges.add: Stunned (debuff, duration 1) on the enemy. Stunned enemies cannot act next turn (describe their inability to respond). Apply -5 bonus damage to the stunning hit. Cooldown 1.' },
    10: { name: 'Purity of Body', description: 'Your mastery of the Ki flowing through you makes you immune to disease and poison.', mechanic: 'The Monk cannot be Poisoned or Diseased. Prevent those statusEffects from being applied. Additionally, at this mastery level, stunning strikes now work on bosses (normally immune). Narrate the ki flowing as a purifying force.' },
  },
  Sorcerer: {
    1: { name: 'Sorcerous Origin', description: 'Innate magical power flows through you, granting bonus spells and shaping your magical abilities.', mechanic: 'The Sorcerer\'s spells hit harder than other casters: add +3 to all spell hpChange values. Once per scene, a spell can be cast for free (innate power surges through them). Narrate the raw, uncontrolled surge of arcane heritage.' },
    3: { name: 'Font of Magic', description: 'Draw on your Sorcery Points to create spell slots or fuel metamagic options.', mechanic: 'The Sorcerer can push a spell beyond its normal limits: double a spell\'s hpChange once per scene (e.g., -12 becomes -24). Narrate the Sorcerer burning through raw magical reserves, briefly draining them (statusEffectChanges.add: Taxed, debuff, duration 1). Cooldown 2.' },
    5: { name: 'Metamagic', description: 'Twist spells with Metamagic options: Quicken, Twin, Empower, Extend, and more.', mechanic: 'Choose one metamagic effect per cast:\n• Quicken: cast a spell as a bonus action (act twice this turn).\n• Twin: affect two targets with a single-target spell (double hpChange spread).\n• Empower: reroll damage dice, keep highest (add +4 to hpChange). Narrate the spell bending to their will.' },
    10: { name: 'Empowered Spell', description: 'Spend 1 Sorcery Point to reroll up to your Charisma modifier damage dice when you cast a spell.', mechanic: 'When a spell\'s damage roll is low, the Sorcerer can push more power through it. Add +6 to any spell\'s hpChange (representing the reroll always improving). Narrate the spell erupting with unexpected ferocity.' },
  },
  Warlock: {
    1: { name: 'Eldritch Blast', description: 'Hurl a beam of crackling energy dealing 1d10 force damage — your signature cantrip that scales with level.', mechanic: 'Eldritch Blast deals -8 damage (1d10 avg). At level 5+ it fires two beams: -14 total. At level 10+ three beams: -20 total. The blast ignores cover and armor. Narrate the crackling void-energy tearing through the target.' },
    3: { name: 'Eldritch Invocations', description: 'Choose two Eldritch Invocations to augment your powers, such as Agonizing Blast or Devil\'s Sight.', mechanic: 'The Warlock has two permanent enhancements (player chooses flavor). Default: Agonizing Blast (+CHA mod to Eldritch Blast = +2 damage) and Devil\'s Sight (see perfectly in magical darkness, cannot be blinded). Apply +2 to all Eldritch Blast hpChange. Narrate as patron-granted dark gifts.' },
    5: { name: 'Pact Boon', description: 'Your patron grants a lasting boon: the Pact of the Blade, Chain, or Tome.', mechanic: 'Three options (player\'s choice of flavor):\n• Blade: melee attacks deal +5 damage, weapon is magical.\n• Chain: a familiar aids them — can scout, distract enemies (-2 to enemy hpChange they deal).\n• Tome: +2 to all knowledge/lore rolls, can cast one extra cantrip. Narrate the patron\'s mark of favor.' },
    10: { name: 'Mystic Arcanum', description: 'Your patron grants a 6th-level spell you can cast once per long rest without expending a spell slot.', mechanic: 'Once per act, the Warlock channels a patron-level spell: massive effect (hpChange -25 to -30 damage, or dramatic narrative consequence), or equivalent healing/utility. This is the patron\'s most direct intervention. Narrate as terrifying patron power, briefly glimpsing their true nature. Cooldown: once per act.' },
  },
}

export function getAbilityForLevel(cls: string, level: number): import('./types').Ability | null {
  const milestones = [1, 3, 5, 10]
  if (!milestones.includes(level)) return null
  return CLASS_ABILITIES[cls]?.[level] ?? null
}
